routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TestimonyController;
use \App\Http\Controllers\CategoriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Web page */
/*View*/
Route::get('/', [\App\Http\Controllers\Web\HomeController::class, 'index'])->name('home');

Route::get('/shop', [\App\Http\Controllers\Web\ShopController::class, 'index'])->name('shop');
Route::get('/cart', [\App\Http\Controllers\Web\CartController::class, 'index'])->name('cart');
Route::get('/about', function () {
    return view('web.pages.about');
})->name('about');
Route::get('/contact', function () {
    return view('web.pages.contact');
})->name('contact');

Route::get('/like/{id}', [\App\Http\Controllers\Web\HomeController::class, 'likeProduct'])->name('like');
Route::get('/unlike/{id}', [\App\Http\Controllers\Web\HomeController::class, 'unLikeProduct'])->name('unlike');

/*Single page*/
Route::get('/product/{id}', [\App\Http\Controllers\Web\SingleController::class, 'detail']);
Route::get('/singe/{product_id}/{size_id}', [\App\Http\Controllers\Web\SingleController::class, 'getPrice']);
Route::post('/add/cart/{id}', [\App\Http\Controllers\Web\CartController::class, 'addToCart']);
/*Shop page*/
Route::get('/shop/{id}', [\App\Http\Controllers\web\ShopController::class, 'shopCategory'])->name('shopCategory');
/*Cart page*/
Route::delete('/cart/delete/{product_id}/{size_id}', [\App\Http\Controllers\Web\CartController::class, 'delete']);
Route::post('/cart/update', [\App\Http\Controllers\Web\CartController::class, 'update']);
/*Checkout page*/
Route::get('/cart/checkout', [\App\Http\Controllers\web\CheckoutController::class, 'index'])->name('checkout');
Route::post('/cart/create', [\App\Http\Controllers\web\CheckoutController::class, 'create'])->name('checkoutCreate');
/*=======================*/


/* Admin page */
Route::get('/admin/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('auth.login');

Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => 'checkRole:admin'], function () {
        Route::get('/admin/', function () {
            return view('admin.dashboard');
        });
        Route::resource('/admin/order', OrderController::class);
        Route::get('/admin/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('auth.logout');
        Route::delete('/admin/delete/{id}', [ProductController::class, 'destroy']);
        Route::resource('/admin/user', UserController::class);
        Route::resource('/admin/category', CategoriesController::class);
        Route::resource('/admin/testimony', TestimonyController::class);
    });
    Route::group(['middleware' => 'checkRole:manager'], function () {
        Route::resource('/admin/product', ProductController::class);
    });
});
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use mysql_xdevapi\Exception;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Categories::paginate(10);
        $data['categories'] = $categories;
        return view('admin.category.list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            $this->validate($request, [
                'name' => 'required',
                'image' => 'required'
            ]);
            $category = new Categories();
            $category->name = $request->name;
            $category->image = $request->image;
            $category->save();
            DB::commit();
            return redirect()->back()->with('message', 'Data added successfully!');
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Categories::find($id);
        if (!$category) {
            abort(404);
        }
        $data['category'] = $category;
        return view('admin.category.detail')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();
            $category = Categories::find($id);
            $this->validate($request, [
                'name' => 'required',
                'image' => 'required'
            ]);
            $category->name = $request->name;
            $category->image = $request->image;
            $category->save();
            DB::commit();
            return redirect()->back()->with('message', 'Data updated successfully!');
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $category = Categories::find($id);
            if (!$category) {
                abort(404);
            }
            $category->delete();
            DB::commit();
            return response()->json([
                'error' => false,
                'message' => "Delete success"
            ]);
        } catch (Exception $e) {
            DB::rollBack();
            return response()->json([
                'error' => true,
                'message' => "Delete success"
            ]);
        }
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.main')
@section('content')
    @if (session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach($errors->all() as $error)
                    <li class="list-group-item" style="color:#ec4844">
                        {{ $error }}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create new product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('category.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group col-md-4">
                            <label>Category Name </label>
                            <input type="text" value="{{ old('name') }}" name="name" class="form-control"
                                   placeholder="Please input category name">
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                   <span class="input-group-btn">
                                     <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                       <i class="fa fa-picture-o"></i> Choose
                                     </a>
                                   </span>
                                <input id="thumbnail" class=" col-md-4 form-control" type="" name="image"
                                       value="{{ old('image') }}">
                            </div>
                            <img id="holder" style="margin-top:15px;max-height:100px;">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script type="text/javascript">
        {{--        image--}}
        $('#lfm').filemanager('file');
        $('#thumbnail').on('change', function (e) {
            $('#holder').attr('src', $(this).val());
        })
    </script>
@endpush

resources/views/admin/category/detail.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Category #{{ $category->id }}-{{ $category->name }}</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{route('category.update', $category)}}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="productname">Product name</label>
                                <input type="text" class="form-control" id="productname" name="name"
                                       value="{{ $category->name }}"/>
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    <div class="input-group">
                                   <span class="input-group-btn">
                                     <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                       <i class="fa fa-picture-o"></i> Choose
                                     </a>
                                   </span>
                                        <input id="thumbnail" class=" col-md-4 form-control" type="" name="image">
                                    </div>
                                    <img id="holder" style="margin-top:15px;max-height:100px;"
                                         src="{{$category->image}}">
                                </div>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div>
                                    <a class="btn btn-default" href="{{ route('category.index') }}">Back</a>
                                </div>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script type="text/javascript">
        $('#lfm').filemanager('file');
        $('#thumbnail').on('change', function (e) {
            $('#holder').attr('src', $(this).val());
        })
    </script>
@endpush

resources/views/admin/category/list.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Product List</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Category Name</th>
                                <th>Image Category</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $count = 0;
                            @endphp
                            @foreach ($categories as $key => $category)
                                <tr>
                                    <td>{{++$count}}</td>
                                    <td>{{ $category->name }}</td>
                                    <td><img src="{{$category->image}}" style="width: 70px; height: 70px"></td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('category.show', $category) }}"
                                           title="Edit"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-danger" href="#" onclick="deleteCategory({{$category->id}})"
                                           title="Delete"><i class="fas fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    {{$categories->links('admin.Layout.pagelist')}}
    <!-- /.row -->
    </div>
@endsection
@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        function deleteCategory(id) {
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this imaginary file!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: '/admin/category/' + id,
                            type: 'DELETE',
                            data: {
                                _token: '{{csrf_token()}}'
                            },
                            success: function (result) {
                                console.log(result.error);
                                if (!result.error) {
                                    swal("Good job!", "Delete product successfully!", "success")
                                        .then((value) => {
                                            location.reload();
                                        });
                                    console.log(result.name);
                                    return;
                                }
                                swal("Oh noes!", "Delete failed product!");

                            }
                        })
                    } else {
                        swal("Your imaginary file is safe!");
                    }
                });
        }
    </script>
@endpush