routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TestimonyController;
use \App\Http\Controllers\CategoriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Web page */
/*View*/
Route::get('/', [\App\Http\Controllers\Web\HomeController::class, 'index'])->name('home');

Route::get('/shop', [\App\Http\Controllers\Web\ShopController::class, 'index'])->name('shop');
Route::get('/cart', [\App\Http\Controllers\Web\CartController::class, 'index'])->name('cart');
Route::get('/about', function () {
    return view('web.pages.about');
})->name('about');
Route::get('/contact', function () {
    return view('web.pages.contact');
})->name('contact');

Route::get('/like/{id}', [\App\Http\Controllers\Web\HomeController::class, 'likeProduct'])->name('like');
Route::get('/unlike/{id}', [\App\Http\Controllers\Web\HomeController::class, 'unLikeProduct'])->name('unlike');

/*Single page*/
Route::get('/product/{id}', [\App\Http\Controllers\Web\SingleController::class, 'detail']);
Route::get('/singe/{product_id}/{size_id}', [\App\Http\Controllers\Web\SingleController::class, 'getPrice']);
Route::post('/add/cart/{id}', [\App\Http\Controllers\Web\CartController::class, 'addToCart']);
/*Shop page*/
Route::get('/shop/{id}', [\App\Http\Controllers\web\ShopController::class, 'shopCategory'])->name('shopCategory');
/*Cart page*/
Route::delete('/cart/delete/{product_id}/{size_id}', [\App\Http\Controllers\Web\CartController::class, 'delete']);
Route::post('/cart/update', [\App\Http\Controllers\Web\CartController::class, 'update']);
/*Checkout page*/
Route::get('/cart/checkout', [\App\Http\Controllers\web\CheckoutController::class, 'index'])->name('checkout');
Route::post('/cart/create', [\App\Http\Controllers\web\CheckoutController::class, 'create'])->name('checkoutCreate');
/*=======================*/


/* Admin page */
Route::get('/admin/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('auth.login');

Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => 'checkRole:admin'], function () {
        Route::get('/admin/', function () {
            return view('admin.dashboard');
        });
        Route::resource('/admin/order', OrderController::class);
        Route::get('/admin/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('auth.logout');
        Route::delete('/admin/delete/{id}', [ProductController::class, 'destroy']);
        Route::resource('/admin/user', UserController::class);
        Route::resource('/admin/category', CategoriesController::class);
        Route::resource('/admin/testimony', TestimonyController::class);
    });
    Route::group(['middleware' => 'checkRole:manager'], function () {
        Route::resource('/admin/product', ProductController::class);
    });
});
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Testimony.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Testimony extends Model
{
    use HasFactory;
    protected $table = 'testimony';
    public function users(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/TestimonyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Testimony;
use Illuminate\Http\Request;

class TestimonyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $testimonys = Testimony::orderBy('created_at', 'desc')->paginate(10);
        $data['testimonys'] = $testimonys;
        return view('admin.testimony.list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $testimony = Testimony::find($id);
        $data['testimony'] = $testimony;
        return view('admin.testimony.detail')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/testimony/detail.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Testimony #{{$testimony->id}} - {{$testimony->users->name}}</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="productname">User Name</label>
                            <p class="form-control">{{$testimony->users->name}}</p>
                        </div>
                        <div class="form-group">
                            <label for="productname">Date Comment</label>
                            <p class="form-control">{{$testimony->created_at->format('d/m/Y')}}</p>
                        </div>
                        <div class="form-group">
                            <label for="productname">Comment Conten</label>
                            <p style="border: 1px solid black; text-align: justify; padding: 10px; border-radius: 10px">{{$testimony->comment}}</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a class="btn btn-default" href="{{ route('testimony.index') }}">Back</a>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
@endsection

resources/views/admin/testimony/list.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Testimony List</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <td>Id User</td>
                                <th>User Name</th>
                                <th>Date Comment</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($testimonys as $key => $testimony)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$testimony->users->id}}</td>
                                    <td>{{$testimony->users->name}}</td>
                                    <td>{{$testimony->created_at->format('d/m/Y')}}</td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('testimony.show', $testimony) }}"
                                           title="Edit"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    {{$testimonys->links('admin.Layout.pagelist')}}
    <!-- /.row -->
    </div>
@endsection