routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TestimonyController;
use \App\Http\Controllers\CategoriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Web page */
/*View*/
Route::get('/', [\App\Http\Controllers\Web\HomeController::class, 'index'])->name('home');

Route::get('/shop', [\App\Http\Controllers\Web\ShopController::class, 'index'])->name('shop');
Route::get('/cart', [\App\Http\Controllers\Web\CartController::class, 'index'])->name('cart');
Route::get('/about', function () {
    return view('web.pages.about');
})->name('about');
Route::get('/contact', function () {
    return view('web.pages.contact');
})->name('contact');

Route::get('/like/{id}', [\App\Http\Controllers\Web\HomeController::class, 'likeProduct'])->name('like');
Route::get('/unlike/{id}', [\App\Http\Controllers\Web\HomeController::class, 'unLikeProduct'])->name('unlike');

/*Single page*/
Route::get('/product/{id}', [\App\Http\Controllers\Web\SingleController::class, 'detail']);
Route::get('/singe/{product_id}/{size_id}', [\App\Http\Controllers\Web\SingleController::class, 'getPrice']);
Route::post('/add/cart/{id}', [\App\Http\Controllers\Web\CartController::class, 'addToCart']);
/*Shop page*/
Route::get('/shop/{id}', [\App\Http\Controllers\web\ShopController::class, 'shopCategory'])->name('shopCategory');
/*Cart page*/
Route::delete('/cart/delete/{product_id}/{size_id}', [\App\Http\Controllers\Web\CartController::class, 'delete']);
Route::post('/cart/update', [\App\Http\Controllers\Web\CartController::class, 'update']);
/*Checkout page*/
Route::get('/cart/checkout', [\App\Http\Controllers\web\CheckoutController::class, 'index'])->name('checkout');
Route::post('/cart/create', [\App\Http\Controllers\web\CheckoutController::class, 'create'])->name('checkoutCreate');
/*=======================*/


/* Admin page */
Route::get('/admin/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('auth.login');

Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => 'checkRole:admin'], function () {
        Route::get('/admin/', function () {
            return view('admin.dashboard');
        });
        Route::resource('/admin/order', OrderController::class);
        Route::get('/admin/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('auth.logout');
        Route::delete('/admin/delete/{id}', [ProductController::class, 'destroy']);
        Route::resource('/admin/user', UserController::class);
        Route::resource('/admin/category', CategoriesController::class);
        Route::resource('/admin/testimony', TestimonyController::class);
    });
    Route::group(['middleware' => 'checkRole:manager'], function () {
        Route::resource('/admin/product', ProductController::class);
    });
});
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
    protected $table = 'orders';
    protected $guarded = [];
    public static $status = [
        "1" => "New",
        "2" => "Warning",
        "3" => "Done"
        ];
    public function user(){
        return $this->belongsTo(User::class, "customer_id");
    }
    public function details(){
        return $this->hasMany(OrderDetail::class, "order_id", "id");
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\OrderDetail;
use App\Models\Product;
use App\Models\ProductDetail;
use App\Models\Size;
use Illuminate\Http\Request;
use App\Models\Order;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::paginate(10);
        $data['orders'] = $orders;
        return view('admin.order.list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.order.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'total' => 'required|numeric',
            'address' => 'required',
            'phone' => 'required|digits:10'
        ]);

        $orders = new Order();
        $orders->total = $request->total;
        $orders->address = $request->address;
        $orders->phone = $request->phone;

        $orders->save();
        return redirect()->back()->with('message', 'Data added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        $data['order'] = $order;
        return view('admin.order.detail')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $orders = Order::find($id);
        $data['order'] = $orders;
        return view('admin.order.edit')->with($data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();
            //tìm order cần update
            $order = Order::find($id);
            //Kiểm tra order tồn tại
            if (!$order) {
                abort(404);
            }

            $total_bill = $order->total;

            $order_detail = OrderDetail::find($request->pk);

            $total_bill -= $order_detail->total;

            $order_detail->qty = $request->value;
            $order_detail->total = $order_detail->qty * $order_detail->product_price;
            $order_detail->save();


            $total_bill +=  $order_detail->total;
            $order->total = $total_bill;
            $order->save();
            DB::commit();
            return response()->json([
                'status' => 'succcess',
                'totalOrder' => $total_bill,
                'itemTotal' => $order_detail->total,
                'idDetail' => $order_detail->id,
            ]);
        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json([
                'status' => 'error',
                'msg' => $e->getMessage()
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/order/create.blade.php
@extends('admin.layouts.app')
    @if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
    @endif
        @if($errors->any())
            <div class="alert alert-danger">
                <ul class="list-group">
                    @foreach($errors->all() as $error)
                        <li class="list-group-item">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{ route('order.store') }}">
        @csrf()
        <div class="form-row">
        <div class="form-group col-md-6">
        <label for="total">Total</label><br>
            <input type="text" class="form-control" name="total" value="{{ old('total') }}">
        </div>
        <div class="form-group col-md-6">
        <label for="address">Address</label>
            <input type="text" class="form-control" name="address" value="{{ old('address') }}">
        </div>
    </div>
    <div class="form-group col-md-6">
    <label for="phone">Phone</label>
        <input type="text" class="form-control" name="phone" value="{{ old('phone') }}">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('orders.index') }}">Back</a>
    </body>
</html>

resources/views/admin/order/detail.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Order #{{ $order->id }}</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{route('order.update', $order)}}" method="POST">
                            @csrf
                            @method("PUT")
                            <table class="col-12">
                                <tr>
                                    <th class="col-3">Customer Name:</th>
                                    <td>{{$order->user->name}}</td>
                                </tr>
                                <tr>
                                    <th class="col-3">Email:</th>
                                    <td>{{$order->user->email}}</td>
                                </tr>
                                <tr>
                                    <th class="col-3">Date Order:</th>
                                    <td>{{Carbon\Carbon::parse($order->order_date)->format('d/m/Y')}}</td>
                                </tr>
                                <tr>
                                    <th class="col-3">Status:</th>
                                    <td>
                                        <!-- <select class="form-control col-2" name="status">
                                            @foreach(\App\Models\Order::$status as $key => $stt)
                                                <option
                                                    value="{{$key}}" {{$order->status == $key ? 'selected':''}}>{{$stt}}</option>
                                            @endforeach
                                        </select> -->
                                        <a href="#" id="status" data-type="select" data-pk="{{$order->id}}"
                                           data-title="Select status"></a>
                                    </td>
                                </tr>
                            </table>
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Product Name</th>
                                    <th>Product Size</th>
                                    <th>Product Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($order->details as $key => $detail)
                                    <tr class="item-{{ $detail->id }}" data-id="{{ $detail->id }}">
                                        <td>{{++$key}}</td>
                                        <td>{{$detail->product_name}}
                                            <input type="hidden" value="{{$detail->id}}" name="details_id[]"/>
                                        </td>
                                        <td>{{$detail->product_size}}</td>
                                        <td class="item-price" data-price="{{ $detail->product_price }}">
                                            {{number_format($detail->product_price, 0, ',', '.')}}
                                            VNĐ
                                        </td>
                                        <td>
                                            <!-- <input class="item-qty" type="number" value="{{$detail->qty}}"
                                                   name="quantity[]"> -->
                                            <a href="#" data-pk="{{$detail->id}}" data-value="{{$detail->qty}}" class="qty"></a>
                                        </td>

                                        <td class="item-total" data-itemtotal="{{ $detail->total }}">{{number_format($detail->total, 0, ',', '.')}}
                                            VNĐ
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tr>
                                    <th colspan="5">Total Bill:</th>
                                    <td id="total_bill" data-total="{{ $order->total }}">{{number_format($order->total, 0, ',', '.')}} VNĐ</td>
                                </tr>
                            </table>
                            <div class="d-flex justify-content-between">
                                <div>
                                    <a class="btn btn-default" href="{{ route('order.index') }}">Back</a>
                                </div>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script type="text/javascript">
        $.fn.editable.defaults.ajaxOptions = {type: "PUT"};
        $.fn.editable.defaults.params = function (params) {
            params._token = '{{ @csrf_token() }}';
            return params;
        };
        $('.qty').editable({
            type: 'number',
            url: '{{route("order.update", $order)}}',
            success: function(response, newValue) {
                if (response.status == 'error')
                    return response.msg; //msg will be shown in editable form
                console.log(response);
                $('.item-' + response.idDetail).find('.item-total').text(formatCurrency(response.itemTotal));
                $('#total_bill').text(formatCurrency(response.totalOrder));
            }
        });
        $('#status').editable({
            value: {{$order->status}},
            source: [
                    @foreach(\App\Models\Order::$status as $key => $stt)
                {
                    value: {{$key}}, text: '{{$stt}}'
                },
                @endforeach
            ],
            name: "status",
            url: '{{route("order.update", $order)}}',
            success: function (response, newValue) {
                if (response.status == 'error')
                    return response.msg; //msg will be shown in editable form
            }
        });
        function formatCurrency(number) {
            return number.toFixed(1).replace(/\d(?=(\d{3})+\.)/g, '$&,') + " VNĐ";
        }
    </script>
@endpush

resources/views/admin/order/list.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Order List</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Customer</th>
                                <th>Order Date</th>
                                <th>Status</th>
                                <th>Total</th>
                                <th>Detail</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $count = 0;
                            @endphp
                            @foreach ($orders as $key => $order)
                                <tr>
                                    <td>{{++$count}}</td>
                                    <td>{{ $order->user->name }}</td>
                                    <td>{{\Carbon\Carbon::parse($order->order_date)->format('j/m/Y') }}</td>
                                    <td><span class='badge badge-success'>{!! \App\Models\Order::$status[$order->status] !!}</span> </td>
                                    <td>{{number_format($order->total,0,',','.') }} VNĐ</td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('order.show', $order) }}" title="Edit"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $orders->links('admin.Layout.pagelist') }}
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
@endsection