routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TestimonyController;
use \App\Http\Controllers\CategoriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Web page */
/*View*/
Route::get('/', [\App\Http\Controllers\Web\HomeController::class, 'index'])->name('home');

Route::get('/shop', [\App\Http\Controllers\Web\ShopController::class, 'index'])->name('shop');
Route::get('/cart', [\App\Http\Controllers\Web\CartController::class, 'index'])->name('cart');
Route::get('/about', function () {
    return view('web.pages.about');
})->name('about');
Route::get('/contact', function () {
    return view('web.pages.contact');
})->name('contact');

Route::get('/like/{id}', [\App\Http\Controllers\Web\HomeController::class, 'likeProduct'])->name('like');
Route::get('/unlike/{id}', [\App\Http\Controllers\Web\HomeController::class, 'unLikeProduct'])->name('unlike');

/*Single page*/
Route::get('/product/{id}', [\App\Http\Controllers\Web\SingleController::class, 'detail']);
Route::get('/singe/{product_id}/{size_id}', [\App\Http\Controllers\Web\SingleController::class, 'getPrice']);
Route::post('/add/cart/{id}', [\App\Http\Controllers\Web\CartController::class, 'addToCart']);
/*Shop page*/
Route::get('/shop/{id}', [\App\Http\Controllers\web\ShopController::class, 'shopCategory'])->name('shopCategory');
/*Cart page*/
Route::delete('/cart/delete/{product_id}/{size_id}', [\App\Http\Controllers\Web\CartController::class, 'delete']);
Route::post('/cart/update', [\App\Http\Controllers\Web\CartController::class, 'update']);
/*Checkout page*/
Route::get('/cart/checkout', [\App\Http\Controllers\web\CheckoutController::class, 'index'])->name('checkout');
Route::post('/cart/create', [\App\Http\Controllers\web\CheckoutController::class, 'create'])->name('checkoutCreate');
/*=======================*/


/* Admin page */
Route::get('/admin/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('auth.login');

Route::middleware(['auth'])->group(function () {
    Route::group(['middleware' => 'checkRole:admin'], function () {
        Route::get('/admin/', function () {
            return view('admin.dashboard');
        });
        Route::resource('/admin/order', OrderController::class);
        Route::get('/admin/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('auth.logout');
        Route::delete('/admin/delete/{id}', [ProductController::class, 'destroy']);
        Route::resource('/admin/user', UserController::class);
        Route::resource('/admin/category', CategoriesController::class);
        Route::resource('/admin/testimony', TestimonyController::class);
    });
    Route::group(['middleware' => 'checkRole:manager'], function () {
        Route::resource('/admin/product', ProductController::class);
    });
});
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table = 'products';

    public function details() {
        return $this->hasMany(ProductDetail::class, 'product_id', 'id');
    }

    public function category(){
        return $this->belongsTo(Categories::class, 'cate_id', 'id');
    }

    public function minPrice() {
        return number_format($this->details->min('price'), 0, ',', '.');
    }

    public function maxPrice() {
        return number_format($this->details->max('price'), 0, ',', '.');
    }
    public function getPriceOfSize($id_size){
        $product = ProductDetail::where('product_id', $this->id)
            ->where('size_id', $id_size)
            ->first();
        return $product->price;
    }
    public function getQuantityOfSize($id_size){
        $product = ProductDetail::where('product_id', $this->id)
            ->where('size_id', $id_size)
            ->first();
        return $product->quantity;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductDetail;
use App\Models\Size;
use App\Models\Categories;
use DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('created_at', 'desc')->paginate(10);
        $data['products'] = $products;
        return view('admin.product.list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::all();
        $sizes = Size::all();
        $data['categories'] = $categories;
        $data['sizes'] = $sizes;
        return view('admin.product.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'name' => 'required|min:6|max:20',
            'cate_id.*' => 'required|min:1|max:5',
            'price.*' => 'required|numeric',
        ]);
        try {
            DB::beginTransaction();
            //dd($request->hot); //lưu thông tin lấy về vào database, kiểm tra dữ liệu (ko null, price là số)
            $product = new Product();
            $product->name = $request->name;
            $product->cate_id = $request->category;
            $product->image = $request->image;
            $product->save();
            for ($i = 0; $i < count($request->size); $i++) {
                $price = str_replace(".", "", $request->price[$i]);
                $dataInsert = [
                    'product_id' => $product->id,
                    'size_id' => $request->size[$i],
                    'price' => $price
                ];
                $datas[$i] = $dataInsert;
            }
            ProductDetail::insert($datas);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage());
        }
        return redirect()->back()->with('message', 'Data added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        $sizes = Size::all();
        $data['product'] = $product;
        $data['sizes'] = $sizes;
        return view('admin.product.detail')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $data['product'] = $product;
        return view('admin.product.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();
            $product = Product::find($id);
            if (!$product) {
                abort(404);
            }
            $product->name = $request->name;
            $product->image = $request->image;
            $product->save();
            $product_detail = ProductDetail::where("product_id", $id)->delete();
            for ($i = 0; $i < count($request->size); $i++) {
                $price = str_replace(".", "", $request->price[$i]);
                $dataInsert = [
                    'product_id' => $product->id,
                    'size_id' => $request->size[$i],
                    'quantity' => $request->quantity[$i],
                    'price' => $price
                ];
                $datas[$i] = $dataInsert;
            }
            ProductDetail::insert($datas);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage());
        }
        return redirect()->back()->with('message', 'Data updated sucess!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $product_detail = ProductDetail::find($id);
            $product = Product::find($product_detail->product_id);
            $product_detail->delete();
            if (count($product->details) == 0) {
                $product->delete();
            }
            DB::commit();
            return response()->json([
                'error' => false,
                'message' => "Delete success"
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            return response()->json([
                'error' => true,
                'message' => "Delete success"
            ]);

        }

    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.main')
@section('content')
    @if (session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach($errors->all() as $error)
                    <li class="list-group-item" style="color:#ec4844">
                        {{ $error }}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create new product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('product.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group col-md-4">
                            <label for="productCode">Product Name </label>
                            <input type="text" value="{{ old('name') }}" name="name" class="form-control"
                                   id="productName" placeholder="Please input product name">
                        </div>
                        <div class="form-group">
                            <label>Categories</label>
                            <select class="form-control col-md-4" name="category">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                   <span class="input-group-btn">
                                     <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                       <i class="fa fa-picture-o"></i> Choose
                                     </a>
                                   </span>
                                <input id="thumbnail" class=" col-md-4 form-control" type="" name="image">
                            </div>
                            <img id="holder" style="margin-top:15px;max-height:100px;">
                        </div>
                        <div id="add_item">
                            @php $check = true;
                            @endphp
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="size">Size</label>
                                    <select class="form-control" name="size[]">
                                        @foreach($sizes as $size)
                                            <option
                                                value="{{ $size->id }}">{{ $size->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="price">Price</label>
                                    <input type="text" class="form-control price" name="price[]" value="0"/>
                                </div>
                                @if($check)
                                    @php $check = !$check; @endphp
                                    <div class="form-group col-md-1 d-flex align-items-end add-button">
                                        <button type="button" onclick="click_function()"
                                                class="btn btn-success btn-outline js-addSize"
                                                style="display: block;height: 40px;"><i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                @else
                                    <div class="form-group col-md-1 d-flex align-items-end">
                                        <button type="button"
                                                class="btn_delete btn btn-danger btn-outline js-addSize"
                                                style="display: block;height: 40px;"><i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script type="text/javascript">
        {{--        image--}}
        $('#lfm').filemanager('file');
        $('#thumbnail').on('change', function (e) {
            $('#holder').attr('src', $(this).val());
        })



        const max_row = 10;
        const add_item = $("#add_item");

        function click_function() {
            let current_row = $('.form-row').length;
            if (current_row < max_row) {
                add_item.append('<div class="form-row">\n' +
                    '                                    <div class="form-group col-md-2">\n' +
                    '                                        <label for="size">Size</label>\n' +
                    '                                        <select class="form-control" name="size[]">\n' +
                    '                                            @foreach($sizes as $size)\n' +
                    '                                                <option value="{{ $size->id }}" >{{ $size->name }}</option>\n' +
                    '                                            @endforeach\n' +
                    '                                        </select>\n' +
                    '                                    </div>\n' +
                    '                                    <div class="form-group col-md-2">\n' +
                    '                                        <label for="price">Price</label>\n' +
                    '                                        <input type="text" class="form-control price" name="price[]" value="0" />\n' +
                    '                                    </div>\n' +
                    '                                    <div class="form-group col-md-1 d-flex align-items-end btn_deletes">\n' +
                    '                                        <button type="button" class="btn_delete btn btn-danger btn-outline js-addSize" style="display: block;height: 40px;"><i class="fa fa-minus"></i></button>\n' +
                    '                                    </div>\n' +
                    '                                </div>');
                $(".btn_delete").click(function () {
                    if ($('.form-row').length > 1) {
                        $(this).closest('.form-row').remove();
                    }
                })
            }
        }

        $(document).ready(function () {
            $(".btn_delete").click(function () {
                if ($('.form-row').length > 1) {
                    $(this).closest('.form-row').remove();
                }
            })
        })

        function remove_function() {
            $(".price").attr('value', '');
            $('#productname').attr('value', '');
        }

    </script>
@endpush

resources/views/admin/product/detail.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Product #{{ $product->id }}-{{ $product->name }}</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{route('product.update', $product)}}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="productname">Product name</label>
                                <input type="text" class="form-control" id="productname" name="name"
                                       value="{{ $product->name }}"/>
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    <div class="input-group">
                                   <span class="input-group-btn">
                                     <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                       <i class="fa fa-picture-o"></i> Choose
                                     </a>
                                   </span>
                                        <input id="thumbnail" class=" col-md-4 form-control" type="" name="image">
                                    </div>
                                    <img id="holder" style="margin-top:15px;max-height:100px;"
                                         src="{{$product->image}}">
                                </div>
                            </div>
                            <div id="add_item">
                                @php $check = true;
                                @endphp
                                @foreach($product->details as $detail)
                                    <div class="form-row">
                                        <div class="form-group col-md-2">
                                            <label for="size">Size</label>
                                            <select class="form-control" name="size[]">
                                                @foreach($sizes as $size)
                                                    <option
                                                        value="{{ $size->id }}" {{ $detail->size_id == $size->id ? "selected" : "" }}>{{ $size->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="price">Price</label>
                                            <input type="text" class="form-control price" name="price[]"
                                                   value="{{ number_format($detail->price, 0, ',', '.') }}"/>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="price">Quantity</label>
                                            <input type="text" class="form-control price" name="quantity[]"
                                                   value="{{$detail->quantity}}"/>
                                        </div>
                                        @if($check)
                                            @php $check = !$check; @endphp
                                            <div class="form-group col-md-1 d-flex align-items-end add-button">
                                                <button type="button" onclick="click_function()"
                                                        class="btn btn-success btn-outline js-addSize"
                                                        style="display: block;height: 40px;"><i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        @else
                                            <div class="form-group col-md-1 d-flex align-items-end">
                                                <button type="button"
                                                        class="btn_delete btn btn-danger btn-outline js-addSize"
                                                        style="display: block;height: 40px;"><i class="fa fa-minus"></i>
                                                </button>
                                            </div>
                                        @endif
                                    </div>
                                @endforeach
                            </div>
                            <div class="d-flex justify-content-between">
                                <div>
                                    <a class="btn btn-default" href="{{ route('product.index') }}">Back</a>
                                    <button type="button" class="btn btn-default" onclick="remove_function()">Reset
                                    </button>
                                </div>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script type="text/javascript">
        $('#lfm').filemanager('file');
        $('#thumbnail').on('change', function (e) {
            $('#holder').attr('src', $(this).val());
        })


        const max_row = 10;
        const add_item = $("#add_item");

        function click_function() {
            let current_row = $('.form-row').length;
            if (current_row < max_row) {
                add_item.append('<div class="form-row">\n' +
                    '                                    <div class="form-group col-md-2">\n' +
                    '                                        <label for="size">Size</label>\n' +
                    '                                        <select class="form-control" name="size[]">\n' +
                    '                                            @foreach($sizes as $size)\n' +
                    '                                                <option value="{{ $size->id }}" >{{ $size->name }}</option>\n' +
                    '                                            @endforeach\n' +
                    '                                        </select>\n' +
                    '                                    </div>\n' +
                    '                                    <div class="form-group col-md-2">\n' +
                    '                                        <label for="price">Price</label>\n' +
                    '                                        <input type="text" class="form-control price" name="price[]" value="0" />\n' +
                    '                                    </div>\n' +
                    '                                    <div class="form-group col-md-1 d-flex align-items-end btn_deletes">\n' +
                    '                                        <button type="button" class="btn_delete btn btn-danger btn-outline js-addSize" style="display: block;height: 40px;"><i class="fa fa-minus"></i></button>\n' +
                    '                                    </div>\n' +
                    '                                </div>');
                $(".btn_delete").click(function () {
                    if ($('.form-row').length > 1) {
                        $(this).closest('.form-row').remove();
                    }
                })
            }
        }

        $(document).ready(function () {
            $(".btn_delete").click(function () {
                if ($('.form-row').length > 1) {
                    $(this).closest('.form-row').remove();
                }
            })
        })

        function remove_function() {
            $(".price").attr('value', '');
            $('#productname').attr('value', '');
        }

    </script>
@endpush

resources/views/admin/product/list.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Product List</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Product Name</th>
                                <th>Image Product</th>
                                <th>Price</th>
                                <th>Size</th>
                                <th>Quantity</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $count = 0;
                            @endphp
                            @foreach ($products as $key => $product)
                                @foreach($product->details as $detail)
                                    <tr>
                                        <td>{{++$count}}</td>
                                        <td>{{ $product->name }}</td>
                                        <td><img src="{{$product->image}}" style="width: 70px; height: 70px"></td>
                                        <td>{{ number_format($detail->price, 0, ',', '.') }}</td>
                                        <td>{{ $detail->size->name }}</td>
                                        <td>{{$detail->quantity}}</td>
                                        <td>
                                            <a class="btn btn-success" href="{{ route('product.show', $product) }}"
                                               title="Edit"><i class="fa fa-edit"></i></a>
                                            <a class="btn btn-danger" href="#" onclick="deleteProduct({{$detail->id}})"
                                               title="Delete"><i class="fas fa-trash-alt"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    {{$products->links('admin.Layout.pagelist')}}
    <!-- /.row -->
    </div>
@endsection
@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        function deleteProduct(id) {
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this imaginary file!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: '/admin/product/' + id,
                            type: 'DELETE',
                            data: {
                                _token: '{{csrf_token()}}'
                            },
                            success: function (result) {
                                console.log(result.error);
                                if (!result.error) {
                                    swal("Good job!", "Delete product successfully!", "success")
                                        .then((value) => {
                                            location.reload();
                                        });
                                    console.log(result.name);
                                    return;
                                }
                                swal("Oh noes!", "Delete failed product!");

                            }
                        })
                    } else {
                        swal("Your imaginary file is safe!");
                    }
                });
        }
    </script>
@endpush